/**
 * Точки интереса (POI) вдоль маршрута.
 * Привязка к программам GO-SHIP / GEOTRACES / WOCE и рецензируемым публикациям.
 * ref — краткая ссылка на источник; doi — где применимо.
 */
export const POIS = [
  // ── Средиземноморье / Атлантика (старт) ──
  {
    id: 'poi-gibraltar',
    name: 'Гибралтарский пролив',
    lat: 35.95, lon: -5.75, type: 'strait',
    note: 'Обмен Средиземного моря и Атлантики, MOW',
    ref: 'Reid (1979) Deep-Sea Res.; WOCE A07',
  },
  {
    id: 'poi-canaries-upw',
    name: 'Канарское upwelling',
    lat: 28.5, lon: -16.0, type: 'upwelling',
    note: 'Постоянный ветровой подъём, высокая продуктивность',
    ref: 'Barton et al. (1998) Prog. Oceanogr.; IMROP',
  },
  {
    id: 'poi-sahara-dust',
    name: 'Пылевая плазма Сахары',
    lat: 22.0, lon: -20.0, type: 'dust',
    note: 'Aeolian Fe и TEIs в поверхностные воды',
    ref: 'GEOTRACES GA06; Measures et al. (2015) Prog. Oceanogr.',
    doi: '10.1016/j.pocean.2014.07.001',
  },
  {
    id: 'poi-mauritanian-upw',
    name: 'Мавританское upwelling',
    lat: 20.0, lon: -18.5, type: 'upwelling',
    note: 'Сезонный подъём, OMZ у margin',
    ref: 'Mittelstaedt (1991) J. Mar. Res.; GEOTRACES GA06',
  },
  {
    id: 'poi-cape-verde-front',
    name: 'Кабо-Верде фронт',
    lat: 16.5, lon: -24.5, type: 'current',
    note: 'Граница тропических вод и upwelling',
    ref: 'Peña-Izquierdo et al. (2012) J. Geophys. Res.',
  },

  // ── Центральная Атлантика ──
  {
    id: 'poi-equator-atl',
    name: 'Экваториальная Атлантика',
    lat: 0.0, lon: -25.0, type: 'equator',
    note: 'EUC, ITCZ, мелкомасштабная вариабельность',
    ref: 'GO-SHIP A16N/WOCE A16 (Talley et al. 2016)',
  },
  {
    id: 'poi-mar-hydrothermal',
    name: 'Срединно-атлантический хребет',
    lat: 14.67, lon: -44.83, type: 'hydrothermal',
    note: 'Rainbow/Saldanha — гидротермальные источники',
    ref: 'GEOTRACES GA03; Rijkenberg et al. (2014) Deep-Sea Res. II',
    doi: '10.1016/j.dsr2.2014.07.005',
  },
  {
    id: 'poi-tag-vent',
    name: 'TAG гидротермальное поле',
    lat: 26.14, lon: -44.82, type: 'hydrothermal',
    note: 'Крупнейшее поле на MAR, Fe/Mn plume',
    ref: 'German et al. (2016) Annu. Rev. Mar. Sci.',
  },
  {
    id: 'poi-goship-a16n',
    name: 'GO-SHIP линия A16N',
    lat: 10.0, lon: -23.0, type: 'goship',
    note: 'Меридиональный разрез 6°S–63°N, decadal repeat',
    ref: 'GO-SHIP/Sloyan et al. (2019) Front. Mar. Sci.',
    doi: '10.3389/fmars.2019.00445',
  },

  // ── Карибы / Панама ──
  {
    id: 'poi-caribbean-llc',
    name: 'Карибское мало-CLH',
    lat: 14.0, lon: -65.0, type: 'gyre',
    note: 'Оligotrophic gyre, N2 fixation',
    ref: 'Capone et al. (2005) Limnol. Oceanogr.',
  },
  {
    id: 'poi-orinoco-plume',
    name: 'Влияние Orinoco',
    lat: 12.5, lon: -62.0, type: 'river',
    note: 'CDOM, nutrients, trace metals с shelf',
    ref: 'Muller-Karger et al. (1989) J. Geophys. Res.',
  },
  {
    id: 'poi-panama-basin',
    name: 'Панамский бассейн',
    lat: 7.0, lon: -81.0, type: 'deep',
    note: 'Изолированная deep water, низкий O2',
    ref: 'Fiedler & Talley (2006) Prog. Oceanogr.',
  },
  {
    id: 'poi-panama-mix',
    name: 'Панамский канал — смешение',
    lat: 9.1, lon: -79.7, type: 'strait',
    note: 'Соединение бассейнов, инвазии, salinity contrast',
    ref: 'Lessios (2008) Annu. Rev. Ecol. Evol. Syst.',
  },

  // ── Тихий океан (восток) ──
  {
    id: 'poi-galapagos-ime',
    name: 'Galápagos island-mass effect',
    lat: -0.5, lon: -90.5, type: 'upwelling',
    note: 'EUC/Cromwell upwelling, HNLC → bloom',
    ref: 'Gordon et al. (1998); Palacios (2002) Geophys. Res. Lett.',
    doi: '10.1029/2002GL016232',
  },
  {
    id: 'poi-cromwell-core',
    name: 'Cromwell Current (EUC)',
    lat: 0.0, lon: -95.0, type: 'current',
    note: 'Восточный подповерхностный ток, Fe-rich core',
    ref: 'Cromwell (1953); Kessler (2006) Prog. Oceanogr.',
  },
  {
    id: 'poi-epr-superfast',
    name: 'East Pacific Rise (superfast)',
    lat: -12.8, lon: -103.9, type: 'hydrothermal',
    note: 'Максимальный гидротермальный flux на Земле',
    ref: 'Resing et al. (2015) Nature Geosci.; GP16',
    doi: '10.1038/ngeo2483',
  },
  {
    id: 'poi-gp16-plume',
    name: 'GP16 гидротермальная плазма',
    lat: -8.0, lon: -110.0, type: 'geotraces',
    note: 'dFe/dMn транспорт >4000 км на запад',
    ref: 'US GEOTRACES GP16 (Moffett et al. 2013)',
  },
  {
    id: 'poi-peru-odz',
    name: 'Peru ODZ (подход)',
    lat: -10.0, lon: -85.0, type: 'omz',
    note: 'Крупнейшая стационарная OMZ вост. Тихого океана',
    ref: 'Karstensen et al. (2008) Biogeosciences; GP16',
  },
  {
    id: 'poi-equator-pac',
    name: 'Тихоокеанский экватор',
    lat: 0.0, lon: -140.0, type: 'equator',
    note: 'TAO/TRITON коридор ENSO',
    ref: 'McPhaden et al. (1998) Bull. AMS (TAO array)',
  },
  {
    id: 'poi-hnlc-pac',
    name: 'Equatorial HNLC province',
    lat: -2.0, lon: -125.0, type: 'biogeochem',
    note: 'High-nutrient low-chlorophyll, Fe limitation',
    ref: 'Martin & Fitzwater (1988) Nature; GEOTRACES',
  },

  // ── Центральный / западный Тихий океан ──
  {
    id: 'poi-spg-core',
    name: 'Южный тихоокеанский gyre',
    lat: -25.0, lon: -130.0, type: 'gyre',
    note: 'Наименее продуктивный gyre, микропластик',
    ref: 'Morel et al. (2010) Biogeosciences; SPG studies',
  },
  {
    id: 'poi-south-pac-omz',
    name: 'Южная тропическая OMZ',
    lat: -15.0, lon: -160.0, type: 'omz',
    note: 'Oxygen minimum, N-loss processes',
    ref: 'Karstensen et al. (2008); GO-SHIP P18',
  },
  {
    id: 'poi-spczz',
    name: 'South Pacific Convergence Zone',
    lat: -18.0, lon: -155.0, type: 'climate',
    note: 'SPCZ — осадки, freshwater flux',
    ref: 'Vincent et al. (2013) J. Climate',
  },
  {
    id: 'poi-tahiti-gp16-end',
    name: 'GP16 финиш (около Таити)',
    lat: -5.0, lon: -150.0, type: 'geotraces',
    note: 'Западный конец EPZT, oligotrophic gyre',
    ref: 'US GEOTRACES GP16 (Jenkins et al. 2016)',
  },
  {
    id: 'poi-lau-basin',
    name: 'Basin Lau (Фиджи)',
    lat: -18.5, lon: -175.0, type: 'deep',
    note: 'Back-arc spreading, гидротермальная активность',
    ref: 'German et al. (2011) Oceanography',
  },
  {
    id: 'poi-dateline-cross',
    name: 'Переход 180° меридиан',
    lat: -16.0, lon: 179.0, type: 'equator',
    note: 'West Pacific Warm Pool boundary region',
    ref: 'GO-SHIP P15; Talley et al. (2016)',
  },

  // ── Австралия / ЮВА ──
  {
    id: 'poi-coral-sea',
    name: 'Коралловое море',
    lat: -16.0, lon: 152.0, type: 'coral',
    note: 'GBR plume, shelf-reef biogeochemistry',
    ref: 'Alongi et al. (2015) Cont. Shelf Res.',
  },
  {
    id: 'poi-torres-mix',
    name: 'Торресов пролив',
    lat: -10.5, lon: 142.5, type: 'strait',
    note: 'Сильные приливные токи, мелководный mixing',
    ref: 'Wolanski (1994) Estuarine Coastal Shelf Sci.',
  },
  {
    id: 'poi-arfura',
    name: 'Арафурское море',
    lat: -9.5, lon: 133.0, type: 'shelf',
    note: 'Муссонное смешение, высокая турбidity',
    ref: 'Alongi et al. (2011) Cont. Shelf Res.',
  },
  {
    id: 'poi-andaman',
    name: 'Андaman Sea',
    lat: 10.0, lon: 97.0, type: 'monsoon',
    note: 'Муссон, internal waves, OMZ на margin',
    ref: 'Jensen et al. (2014) Deep-Sea Res. I',
  },
  {
    id: 'poi-goship-i09n',
    name: 'GO-SHIP I09N (95°E)',
    lat: 5.0, lon: 95.0, type: 'goship',
    note: 'Меридиональный разрез IO, repeat hydrography',
    ref: 'GO-SHIP I09N (Menezes et al. 2025 cruise)',
  },
  {
    id: 'poi-bay-bengal',
    name: 'Бengальский залив',
    lat: 15.0, lon: 88.0, type: 'river',
    note: 'Ganges-Brahmaputra plume, stratification',
    ref: 'Mukhopadhyay et al. (2002) Deep-Sea Res. I',
  },
  {
    id: 'poi-sumatra-upw',
    name: 'Sumatra upwelling',
    lat: 0.0, lon: 98.0, type: 'upwelling',
    note: 'Муссонный подъём, IOD teleconnections',
    ref: 'Susanto et al. (2001) Geophys. Res. Lett.',
  },

  // ── Индийский океан ──
  {
    id: 'poi-sri-lanka-dome',
    name: 'Sri Lanka dome',
    lat: 5.5, lon: 82.0, type: 'upwelling',
    note: 'Муссонный dome, высокая продуктивность',
    ref: 'Vinayachandran & Mathew (2003) Deep-Sea Res. I',
  },
  {
    id: 'poi-equator-io',
    name: 'Экваториальный IO',
    lat: 0.0, lon: 70.0, type: 'equator',
    note: 'Wyrtki jets, IOD, asymmetric circulation',
    ref: 'Schott et al. (2009) Prog. Oceanogr.',
  },
  {
    id: 'poi-chagos',
    name: 'Chagos-Laccadive ridge',
    lat: -5.0, lon: 72.0, type: 'ridge',
    note: 'Island mass effect, mesoscale eddies',
    ref: 'GEOTRACES GI04; Resing et al. (2019)',
  },
  {
    id: 'poi-indian-gyre',
    name: 'Центр антициклона IO',
    lat: -15.0, lon: 80.0, type: 'gyre',
    note: 'Debris accumulation, heat content',
    ref: 'GO-SHIP I07N; IPCC AR6 Indian Ocean',
  },
  {
    id: 'poi-arabian-omz',
    name: 'Аравийская OMZ',
    lat: 18.0, lon: 62.0, type: 'omz',
    note: 'Иntense denitrification, seasonal O2 drawdown',
    ref: 'Bristow et al. (2017) Nature; GO-SHIP I08N',
    doi: '10.1038/nature23875',
  },
  {
    id: 'poi-oman-eddy',
    name: 'Oman Sea eddy',
    lat: 22.0, lon: 59.5, type: 'eddy',
    note: 'Mesoscale eddies, upwelling filaments',
    ref: 'Vic et al. (2014) J. Geophys. Res. Oceans',
  },
  {
    id: 'poi-mascrene',
    name: 'Mascarene plateau',
    lat: -12.0, lon: 60.0, type: 'ridge',
    note: 'Topographic steering, internal tides',
    ref: 'GEOTRACES GIpr05 process study',
  },

  // ── Красное море / Средиземноморье (финиш) ──
  {
    id: 'poi-bab-el-mandeb',
    name: 'Bab el-Mandeb',
    lat: 12.58, lon: 43.33, type: 'strait',
    note: 'Red Sea Overflow Water, exchange IO–RS',
    ref: 'Georgiou et al. (2016) J. Geophys. Res. Oceans',
  },
  {
    id: 'poi-gulf-aden',
    name: 'Аden Gulf upwelling',
    lat: 12.5, lon: 45.0, type: 'upwelling',
    note: 'Сомалийский апwelling system (seasonal)',
    ref: 'Swallow & Bruce (1966) Deep-Sea Res.',
  },
  {
    id: 'poi-red-sea-salt',
    name: 'Красное море — солёность',
    lat: 22.0, lon: 38.0, type: 'basin',
    note: 'Экстремальная солёность, coral refugia',
    ref: 'Woelk & Quadfasel (1996) J. Geophys. Res.',
  },
  {
    id: 'poi-atlantis-ii',
    name: 'Atlantis II Deep',
    lat: 21.35, lon: 38.42, type: 'hydrothermal',
    note: 'Горячие brines, металлы в осадках',
    ref: 'Hartmann et al. (1998) Deep-Sea Res. I',
  },
  {
    id: 'poi-suez-outflow',
    name: 'Суэц — выход в Средиземное море',
    lat: 31.3, lon: 32.3, type: 'strait',
    note: 'Lessepsian migration corridor, salinity flux',
    ref: 'Millot & Taupier-Letage (2005)',
  },
  {
    id: 'poi-e-med-gyre',
    name: 'Восточное Средиземноморье',
    lat: 34.0, lon: 30.0, type: 'basin',
    note: 'Levantine Intermediate Water formation',
    ref: 'Roether et al. (1996) Prog. Oceanogr.',
  },
  {
    id: 'poi-nile-plume',
    name: 'Nile plume (Levant)',
    lat: 33.5, lon: 32.0, type: 'river',
    note: 'Nutrients, eutrophication eastern Med',
    ref: 'Halim et al. (1967) Deep-Sea Res.',
  },

  // ── Глубоководные / дополнительные ──
  {
    id: 'poi-mariana-trench',
    name: 'Mariana Trench (подход)',
    lat: 11.35, lon: 142.2, type: 'deep',
    note: 'Hadal zone, Challenger Deep region',
    ref: 'Glud et al. (2021) Nature Geosci.',
    doi: '10.1038/s41561-021-00722-z',
  },
  {
    id: 'poi-clipperton',
    name: 'Clipperton Fracture Zone',
    lat: 10.0, lon: -108.0, type: 'ridge',
    note: 'Транспорт deep water через fracture',
    ref: 'Lonsdale (1976) Tectonophysics; GP16',
  },
  {
    id: 'poi-argo-float',
    name: 'Argo / GO-BGC float zone',
    lat: -20.0, lon: -120.0, type: 'observatory',
    note: 'Калибровка автономных BGC-float',
    ref: 'Claustre et al. (2020) Front. Mar. Sci. (GO-BGC)',
    doi: '10.3389/fmars.2020.00593',
  },
  {
    id: 'poi-microplast-spg',
    name: 'Great Pacific Garbage Patch (юг)',
    lat: -30.0, lon: -145.0, type: 'pollution',
    note: 'Accumulation zone микропластика',
    ref: 'Lebreton et al. (2018) Sci. Rep.',
    doi: '10.1038/s41598-018-22939-w',
  },
];

/** Типы POI для легенды */
export const POI_TYPES = {
  upwelling: 'Upwelling',
  equator: 'Экватор',
  hydrothermal: 'Гидротерм.',
  ridge: 'Хребет',
  deep: 'Глубоководье',
  gyre: 'Anticyclone',
  omz: 'OMZ',
  strait: 'Пролив',
  goship: 'GO-SHIP',
  geotraces: 'GEOTRACES',
  dust: 'Aeolian dust',
  river: 'River plume',
  current: 'Течение',
  monsoon: 'Муссон',
  coral: 'Коралловый shelf',
  shelf: 'Шельф',
  climate: 'Climate zone',
  biogeochem: 'Biogeochem',
  basin: 'Basin',
  eddy: 'Eddy',
  observatory: 'Argo/obs',
  pollution: 'Pollution',
};
